<?php
/** @package W2o::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("FeriaMap.php");

/**
 * FeriaDAO provides object-oriented access to the feria table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package W2o::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class FeriaDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var int */
	public $Professorid;

	/** @var date */
	public $Datainicio;

	/** @var date */
	public $Datafim;


	/**
	 * Returns the foreign object based on the value of Professorid
	 * @return Professor
	 */
	public function GetIdProfessor()
	{
		return $this->_phreezer->GetManyToOne($this, "FK__professor");
	}


}
?>